apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cfp-goa-ingress
  namespace: cfp
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: cfp-traefik
  tls:
    - secretName: desa-tls-secret
  rules:
    - host: desa.cfp.upv.es
      http:
        paths:
          - path: /cfp-goa/
            pathType: Prefix
            backend:
              service:
                name: cfp-goa-service
                port:
                  number: 8080
