apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: dummy-post-office-namespace
data:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "mydatabase"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: dummy-post-office-namespace
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS messages (
        id SERIAL PRIMARY KEY,
        content TEXT NOT NULL,
        from VARCHAR(255) NOT NULL,
        to VARCHAR(255) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        constraint from_to check (from <> to),
        constraint from_check CHECK (position('@' IN from) > 0),
        constraint to_check CHECK (position('@' IN to) > 0)
    );
