apiVersion: v1
kind: PersistentVolume
metadata:
  name: dummy-post-office-postgresql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /var/snap/microk8s/common/default-storage/dummy-post-office-postgresql
    type: DirectoryOrCreate