apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: dummy-post-office-namespace
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP